"use client";

import type {WishlistItem} from "../../types/wishlist.ts"
import Image from 'next/image';
import {useDispatch, useSelector} from "react-redux"
import { addToCart } from "@/store/cartslice";
import { AppDispatch, RootState } from '@/store/store';
import { fetchWishlist, loadWishlistLocal, toggleWishlistItem } from "@/store/wishlistslice";
import { useEffect, useState } from "react";
import { createClient } from "@/utils/supabase/client";




const AccountWishlist = () => {
    const dispatch = useDispatch<AppDispatch>();
    const wishlist = useSelector((state:RootState) => state.wishlist.items )
    const loading = useSelector((state:RootState) => state.wishlist.loading)
    const [loadingLocal, setLoadingLocal] = useState(true);

    // ✅ Load wishlist on mount
    useEffect(() => {
        const loadWishlist = async () => {
        // 1. Load from local cache
        await dispatch(loadWishlistLocal());
        setLoadingLocal(false)

        // 2. Optionally, if user logged in, fetch from Supabase
        const supabase = createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
            await dispatch(fetchWishlist(user.id));
        }
        };
        loadWishlist();
    }, [dispatch]);


    const handleAddToCart = (item: WishlistItem) => {
        const formatted = {
            id: '', // id will be generated by Supabase
            user_id: item.user_id,
            product_id: item.product_id,
            color: item.color,
            size: item.size,
            amount: 1,
        }

        dispatch(addToCart({userId: item.user_id, item: formatted}));
        dispatch(toggleWishlistItem(item))

    }

    if (loading && loadingLocal) {
        return (
            <div>loading wishlist...</div>
        )
    }



    return (
        <div className='divide-y divide-y-gray-200 w-full max-w-[620px] flex flex-col py-8'>
            {
                wishlist.length === 0 ? (
                    <div className='py-8'>Your wishlist is empty.</div>
                ) : (
                   wishlist.map((item) => (
                    <div className='flex gap-8 py-4 items-center justify-between' key={item.id}>
                        <div className="flex items-center gap-4">
                            <div className='relative  bg-neutral-100 rounded-md'>
                                <Image src={item.products?.image || ''} alt={item.products?.name || 'Product Image'} width={80} height={80} />
                            </div>

                            <div>
                                <p className='justify-start text-gray-900 text-sm font-medium font-inter leading-6'>{item.products?.name}</p>
                                <p className='justify-start text-gray-600 text-xs font-medium font-inter capitalize leading-6'>Added on: {new Date(item.created_at).toLocaleDateString('en-us', {
                                    day: 'numeric',
                                    month: 'short',
                                    year: 'numeric'
                                }) }</p>
                                <button onClick={() => dispatch(toggleWishlistItem(item))} className='justify-start text-gray-900 text-xs font-medium font-inter capitalize leading-6'>
                                    <p>remove item</p>
                                </button>
                            </div>
                        </div>

                        <div className='flex items-center gap-4'>
                            <div className='w-fit flex flex-col gap-1'>
                                <p>${item.products?.price}.00</p>
                            </div>
                           <button className="px-6 py-3 bg-white rounded outline outline-1 outline-offset-[-1px] outline-gray-900 inline-flex justify-start items-center gap-1.5 overflow-hidden" onClick={() => handleAddToCart(item)}>
                                <p className="text-gray-900 text-sm font-medium font-inter leading-6">Add to cart</p>
                           </button>
                        </div>
                    </div>
                   ))
                )
            }
        </div>
    );
};

export default AccountWishlist;